#!/usr/bin/env python3
"""sdlc-validate.py — deterministic validator for SDLC artifacts.

CANONICAL SOURCE: scripts/sdlc-validate.py. The copies under
skills/sdlc-init/ and skills/sdlc-migrate/ are GENERATED by
`scripts/sync_skills.py` (run via `zrb skill sync` before push) — edit this
file, never the copies.

Bundled with the sdlc-* skills and installed into a project at
`.sdlc/tools/sdlc-validate.py`. Run it by hand, from a skill
("validate -> fix -> repeat"), or as a CI gate. Stdlib only; Python 3.8+.

USAGE
    python3 sdlc-validate.py [--root DIR] [--feature SLUG] [--strict] [--json]

    --root DIR     Project root to scan (default: current directory).
    --feature SLUG Restrict checks to one feature directory (default: all).
    --strict       Make warnings exit non-zero too.
    --json         Emit a machine-readable JSON report instead of text.

EXIT CODES
    0  clean (no errors; warnings allowed unless --strict)
    1  warnings present and --strict
    2  errors present

ID & TRACEABILITY SCHEME (see .sdlc/CONVENTIONS.md)
    - Each spec.md declares `**Feature Key:** KEY` (uppercase, globally unique).
    - Requirement IDs are per-feature (REQ-001, NFR-001, UT-001, ...) and made
      globally unambiguous by the key.
    - Source headers:  IMPLEMENTS: KEY:REQ-001, KEY:NFR-002
    - Test headers:    COVERS: KEY:REQ-002, KEY:UT-005, KEY:IT-001
    - Inline tags:     @sdlc KEY:REQ-003, KEY:REQ-004
    - Legacy (unkeyed) tags such as `@sdlc REQ-003` are tolerated with a WARNING.

CHECKS
    1  Feature key uniqueness ........................... ERROR
    2  Traceability: code coverage (IMPLEMENTS) ......... ERROR
    3  Traceability: test coverage (COVERS) ............. ERROR
    4  Dangling tag (references a non-existent ID) ...... ERROR
    5  Unkeyed tag ...................................... WARNING
    6  Duplicate active ID within a feature ............. ERROR
    7  Recycled removed ID .............................. ERROR
    8  EARS syntax (deprecated dialect / no SHALL) ...... WARNING
    9  Test-plan coverage of spec ....................... WARNING
   10  Legacy layout detected ........................... INFO
   11  Missing test plan ................................ WARNING
"""

import argparse
import json
import os
import re
import sys

# --------------------------------------------------------------------------
# Findings
# --------------------------------------------------------------------------
ERROR, WARNING, INFO = "ERROR", "WARNING", "INFO"


class Report:
    def __init__(self):
        self.items = []  # (severity, check, message, location)

    def add(self, severity, check, message, location=""):
        self.items.append((severity, check, message, location))

    def error(self, c, m, loc=""):
        self.add(ERROR, c, m, loc)

    def warn(self, c, m, loc=""):
        self.add(WARNING, c, m, loc)

    def info(self, c, m, loc=""):
        self.add(INFO, c, m, loc)

    def counts(self):
        e = sum(1 for s, *_ in self.items if s == ERROR)
        w = sum(1 for s, *_ in self.items if s == WARNING)
        i = sum(1 for s, *_ in self.items if s == INFO)
        return e, w, i


# --------------------------------------------------------------------------
# Filesystem helpers
# --------------------------------------------------------------------------
SKIP_DIRS = {".git", "node_modules", ".sdlc", "dist", "build",
             "__pycache__", ".venv", "venv", ".mypy_cache", ".pytest_cache",
             "target", ".next", "coverage", ".tox"}
SKIP_EXT = {".png", ".jpg", ".jpeg", ".gif", ".pdf", ".zip", ".gz", ".tar",
            ".lock", ".ico", ".woff", ".woff2", ".ttf", ".eot", ".mp4",
            ".mp3", ".bin", ".so", ".dll", ".dylib", ".class", ".jar",
            ".wasm", ".pyc"}
MAX_BYTES = 2 * 1024 * 1024


def read_text(path):
    try:
        if os.path.getsize(path) > MAX_BYTES:
            return None
        with open(path, "rb") as fh:
            raw = fh.read()
        if b"\x00" in raw:  # binary
            return None
        return raw.decode("utf-8", errors="replace")
    except (OSError, ValueError):
        return None


def first(*paths):
    """Return the first existing path, else None."""
    for p in paths:
        if p and os.path.exists(p):
            return p
    return None


def list_feature_dirs(root):
    """Return {slug: spec_path} for canonical and legacy spec locations."""
    out = {}
    for base in (os.path.join(root, ".sdlc", "specs"),
                 os.path.join(root, "specs")):
        if not os.path.isdir(base):
            continue
        for slug in sorted(os.listdir(base)):
            d = os.path.join(base, slug)
            if not os.path.isdir(d):
                continue
            spec = os.path.join(d, "spec.md")
            if os.path.exists(spec) and slug not in out:
                out[slug] = spec
    return out


def test_plan_for(root, slug):
    return first(
        os.path.join(root, ".sdlc", "tests", slug, "test-plan.md"),
        os.path.join(root, "tests", slug, "test-plan.md"),
    )


# --------------------------------------------------------------------------
# Parsing
# --------------------------------------------------------------------------
KEY_RE = re.compile(r"^\*\*Feature Key:\*\*\s*([A-Z][A-Z0-9_-]*)", re.M)
# An ID token, optionally key-prefixed: KEY:REQ-001  or  REQ-001
TAG_TOKEN_RE = re.compile(r"\b(?:([A-Z][A-Z0-9_-]*):)?((?:REQ|NFR|UT|IT|E2E|PBT)-\d+)\b")
# A requirement/NFR definition line in spec.md
DEF_LINE_RE = re.compile(r"^\s*[-*|]?\s*`?((?:REQ|NFR)-\d+)`?\b(.*)$")
IMPLEMENTS_RE = re.compile(r"IMPLEMENTS:\s*(.+)")
COVERS_RE = re.compile(r"COVERS:\s*(.+)")
SDLC_TAG_RE = re.compile(r"@sdlc\s+(.+)")

DEPRECATED_EARS = [
    (re.compile(r"\bALWAYS\s+SHALL\b", re.I), "ALWAYS SHALL -> ubiquitous (drop ALWAYS): 'The <system> SHALL ...'"),
    (re.compile(r"\bWHERE\b.+\bTHEN\b", re.I), "WHERE ... THEN (state-driven) -> 'WHILE ..., the <system> SHALL ...'"),
    (re.compile(r"\bAS\b.+\bTHEN\b", re.I), "AS ... THEN -> 'IF ..., THEN ... SHALL ...'"),
    (re.compile(r"\bUNLESS\b", re.I), "UNLESS -> 'IF NOT ..., THEN ... SHALL ...' (or WHERE)"),
]
OUTSIDE_CODE_VALIDATORS = re.compile(r"\b(infra|ci|cd|manual|process|sla|slo|terraform|waf|dashboard)\b", re.I)


def parse_spec(text):
    """Return dict: key, active{id:line_no}, removed{set}, removed_text, nfr_outside{set}, req_text{id:text}."""
    key_m = KEY_RE.search(text)
    key = key_m.group(1) if key_m else None

    active = {}        # id -> line number (first active definition)
    dup = []           # ids defined active more than once
    removed = set()
    req_text = {}      # REQ id -> requirement text (active only)
    nfr_outside = set()

    lines = text.splitlines()
    in_outside_section = False
    for idx, line in enumerate(lines, 1):
        stripped = line.strip()
        if stripped.startswith("#"):
            in_outside_section = "validated outside code" in stripped.lower()
        # NFR table row: `| NFR-001 | requirement | target | validated-by |`.
        # If the last (Validated By) cell names an out-of-code mechanism, the
        # NFR is exempt from IMPLEMENTS/COVERS. Done before def-matching because
        # a table row also matches DEF_LINE_RE.
        if "|" in line:
            nonempty = [c.strip() for c in line.split("|") if c.strip()]
            if nonempty and OUTSIDE_CODE_VALIDATORS.search(nonempty[-1]):
                for tok in re.findall(r"\b(NFR-\d+)\b", line):
                    nfr_outside.add(tok)
        m = DEF_LINE_RE.match(line)
        if not m:
            continue
        rid, rest = m.group(1), m.group(2)
        if "REMOVED" in rest.upper():
            removed.add(rid)
            continue
        in_outside = in_outside_section and rid.startswith("NFR-")
        if in_outside:
            nfr_outside.add(rid)
        if rid in active:
            # Re-listing an NFR under "NFRs Validated Outside Code" is expected —
            # it is the same NFR that appears in the NFR table, not a duplicate
            # active definition. Only flag a true redefinition.
            if not in_outside:
                dup.append(rid)
        else:
            active[rid] = idx
        if rid.startswith("REQ-"):
            # requirement text = part after the first ':' following the id
            text_part = rest.split(":", 1)[1].strip() if ":" in rest else rest.strip()
            req_text[rid] = text_part
    return {
        "key": key, "active": active, "dup": dup, "removed": removed,
        "req_text": req_text, "nfr_outside": nfr_outside,
    }


def parse_tags(text):
    """Return lists of (key_or_None, id) for IMPLEMENTS, COVERS, and @sdlc tags."""
    implements, covers, inline = [], [], []
    for line in text.splitlines():
        for regex, bucket in ((IMPLEMENTS_RE, implements),
                              (COVERS_RE, covers),
                              (SDLC_TAG_RE, inline)):
            m = regex.search(line)
            if m:
                for tok in TAG_TOKEN_RE.finditer(m.group(1)):
                    bucket.append((tok.group(1), tok.group(2)))
    return implements, covers, inline


# --------------------------------------------------------------------------
# Main validation
# --------------------------------------------------------------------------
def validate(root, only_feature=None, rpt=None):
    rpt = rpt or Report()

    # --- legacy layout (INFO) ---
    legacy_pairs = [
        (os.path.join(root, "docs"), os.path.join(root, ".sdlc", "docs"), "steering docs"),
        (os.path.join(root, "requirements"), os.path.join(root, ".sdlc", "requirements"), "requirements"),
        (os.path.join(root, "specs"), os.path.join(root, ".sdlc", "specs"), "specs"),
        (os.path.join(root, "reviews"), os.path.join(root, ".sdlc", "reviews"), "reviews"),
        (os.path.join(root, "rules.md"), os.path.join(root, ".sdlc", "rules.md"), "rules"),
    ]
    for legacy, canonical, label in legacy_pairs:
        if os.path.exists(legacy) and not os.path.exists(canonical):
            rpt.info("legacy-layout",
                     "Legacy %s at %s — run /sdlc-migrate to consolidate under .sdlc/."
                     % (label, os.path.relpath(legacy, root)), os.path.relpath(legacy, root))

    # --- discover specs ---
    features = list_feature_dirs(root)
    if only_feature:
        features = {s: p for s, p in features.items() if s == only_feature}
    if not features:
        rpt.info("no-specs", "No SDLC specs found (looked in .sdlc/specs/ and specs/).")
        return rpt

    # --- parse specs, build global ID universe per key ---
    specs = {}            # slug -> parsed
    key_to_slug = {}      # KEY -> slug (for uniqueness + lookup)
    for slug, spec_path in features.items():
        text = read_text(spec_path)
        if text is None:
            rpt.error("read", "Could not read spec", os.path.relpath(spec_path, root))
            continue
        parsed = parse_spec(text)
        key = parsed["key"]
        loc = os.path.relpath(spec_path, root)
        if not key:
            key = slug.upper()
            parsed["key"] = key
            rpt.info("feature-key", "No '**Feature Key:**' declared; defaulting to '%s'. Declare one explicitly." % key, loc)
        # check 1: key uniqueness
        if key in key_to_slug and key_to_slug[key] != slug:
            rpt.error("key-unique", "Feature Key '%s' is also used by feature '%s'." % (key, key_to_slug[key]), loc)
        else:
            key_to_slug[key] = slug
        # check 6: duplicate active id
        for rid in sorted(set(parsed["dup"])):
            rpt.error("dup-id", "ID %s defined more than once (active) in %s." % (rid, slug), loc)
        # check 7: recycled removed id
        for rid in sorted(parsed["removed"] & set(parsed["active"])):
            rpt.error("recycled-id", "ID %s is marked REMOVED but also appears active." % rid, loc)
        # check 8: EARS syntax (REQ only)
        for rid, rtext in parsed["req_text"].items():
            hit = False
            for regex, hint in DEPRECATED_EARS:
                if regex.search(rtext):
                    rpt.warn("ears", "%s uses deprecated EARS dialect (%s)." % (rid, hint), loc)
                    hit = True
                    break
            if hit:
                continue
            if not re.search(r"\bSHALL\b", rtext, re.I):
                rpt.warn("ears", "%s has no SHALL/EARS keyword — restate in canonical EARS." % rid, loc)
        specs[slug] = parsed

    # --- scan source/test files for tags ---
    impl_seen = set()     # (key, id) present in any IMPLEMENTS
    cover_seen = set()    # (key, id) present in any COVERS
    all_tags = []         # (key_or_None, id, kind, file)
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            ext = os.path.splitext(fn)[1].lower()
            if ext in SKIP_EXT:
                continue
            fpath = os.path.join(dirpath, fn)
            text = read_text(fpath)
            if text is None:
                continue
            impl, cov, inline = parse_tags(text)
            rel = os.path.relpath(fpath, root)
            for k, i in impl:
                if k:
                    impl_seen.add((k, i))
                all_tags.append((k, i, "IMPLEMENTS", rel))
            for k, i in cov:
                if k:
                    cover_seen.add((k, i))
                all_tags.append((k, i, "COVERS", rel))
            for k, i in inline:
                all_tags.append((k, i, "@sdlc", rel))

    # build valid (key,id) universe
    valid = set()
    for slug, parsed in specs.items():
        key = parsed["key"]
        for rid in parsed["active"]:
            valid.add((key, rid))
        # also include test-plan IDs as valid targets
        tp = test_plan_for(root, slug)
        if tp:
            tptext = read_text(tp) or ""
            for tok in re.findall(r"\b((?:UT|IT|E2E|PBT)-\d+)\b", tptext):
                valid.add((key, tok))

    # check 4 & 5: dangling / unkeyed tags
    for k, i, kind, rel in all_tags:
        if k is None:
            rpt.warn("unkeyed-tag", "Unkeyed tag '%s' in %s (%s) — re-key as KEY:%s." % (i, kind, kind, i), rel)
            continue
        if (k, i) not in valid:
            if k not in key_to_slug:
                rpt.error("dangling-tag", "Tag %s:%s (%s) references unknown Feature Key '%s'." % (k, i, kind, k), rel)
            else:
                rpt.error("dangling-tag", "Tag %s:%s (%s) references an ID not defined in feature '%s'." % (k, i, kind, key_to_slug[k]), rel)

    # checks 2, 3, 9, 11: coverage per feature
    for slug, parsed in specs.items():
        key = parsed["key"]
        loc = os.path.relpath(features[slug], root)
        tp = test_plan_for(root, slug)
        if not tp:
            rpt.warn("missing-test-plan", "Feature '%s' has spec.md but no test-plan.md." % slug, loc)
            tptext = ""
        else:
            tptext = read_text(tp) or ""
        for rid in sorted(parsed["active"]):
            is_nfr_outside = rid in parsed["nfr_outside"]
            if is_nfr_outside:
                rpt.info("outside-code", "%s:%s validated outside code — exempt from IMPLEMENTS/COVERS." % (key, rid), loc)
                continue
            # check 2: code coverage
            if (key, rid) not in impl_seen:
                rpt.error("trace-code", "%s:%s has no IMPLEMENTS: header in any source file." % (key, rid), loc)
            # check 3: test coverage
            if (key, rid) not in cover_seen:
                rpt.error("trace-test", "%s:%s has no COVERS: header in any test file." % (key, rid), loc)
            # check 9: test-plan reference
            if rid.startswith("REQ-") and tp and rid not in tptext:
                rpt.warn("plan-coverage", "%s not referenced by any row in test-plan.md." % rid, os.path.relpath(tp, root))

    return rpt


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------
def emit_text(rpt):
    order = {ERROR: 0, WARNING: 1, INFO: 2}
    for sev, check, msg, loc in sorted(rpt.items, key=lambda x: order[x[0]]):
        tail = " (%s)" % loc if loc else ""
        print("%s: %s — %s%s" % (sev, check, msg, tail))
    e, w, i = rpt.counts()
    print("\n%d errors, %d warnings, %d info" % (e, w, i))


def emit_json(rpt):
    e, w, i = rpt.counts()
    print(json.dumps({
        "summary": {"errors": e, "warnings": w, "info": i},
        "findings": [
            {"severity": s, "check": c, "message": m, "location": loc}
            for s, c, m, loc in rpt.items
        ],
    }, indent=2))


def main(argv=None):
    ap = argparse.ArgumentParser(description="Validate SDLC traceability, EARS, and ID hygiene.")
    ap.add_argument("--root", default=".", help="project root (default: .)")
    ap.add_argument("--feature", default=None, help="restrict to one feature slug")
    ap.add_argument("--strict", action="store_true", help="warnings exit non-zero too")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    args = ap.parse_args(argv)

    root = os.path.abspath(args.root)
    rpt = validate(root, only_feature=args.feature)

    (emit_json if args.json else emit_text)(rpt)

    e, w, _ = rpt.counts()
    if e:
        return 2
    if w and args.strict:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
